export const ROLES = {
  ADMIN: "ADMIN",
  USER: "USER",
};

export const PRODUCT_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  OUT_OF_STOCK: "OUT_OF_STOCK",
};

export const ORDER_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  PREPARING: "PREPARING",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const PAYMENT_STATUS = {
  UNPAID: "UNPAID",
  PAID: "PAID",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

export const TRANSACTION_TYPE = {
  TOP_UP: "TOP_UP",
  PAYMENT: "PAYMENT",
  RECEIVE_PAYMENT: "RECEIVE_PAYMENT",
  REFUND: "REFUND",
};

export const PAYMENT_METHOD = {
  WALLET: "WALLET",
  CASH_ON_DELIVERY: "CASH_ON_DELIVERY",
  CASH_AT_STORE: "CASH_AT_STORE",
};
